// apps/platform-web/src/components/layout/PageHeader.vue
<script setup lang="ts">
defineProps<{
  title: string
  description: string
  eyebrow?: string
  compact?: boolean
}>()
</script>

<template>
  <header
    class="pw-page-header transition-all duration-200"
    :class="compact ? 'mb-1 gap-1.5 xl:items-center' : ''"
  >
    <div>
      <div
        v-if="eyebrow"
        class="pw-page-eyebrow transition-all duration-200"
        :class="compact ? 'text-[10px] tracking-[0.14em]' : ''"
      >
        {{ eyebrow }}
      </div>
      <h1
        class="pw-page-title mt-1 transition-all duration-200"
        :class="compact ? 'text-[18px] md:text-[20px]' : ''"
      >
        {{ title }}
      </h1>
      <p
        class="pw-page-description transition-all duration-200"
        :class="compact ? 'mt-0 hidden' : ''"
      >
        {{ description }}
      </p>
    </div>
    <div
      v-if="$slots.actions"
      class="flex flex-wrap items-center gap-3 transition-all duration-200"
      :class="compact ? 'gap-1.5' : ''"
    >
      <slot name="actions" />
    </div>
  </header>
</template>

// apps/platform-web-v2/src/components/platform/page-header.tsx
import type { ReactNode } from "react";

import { cn } from "@/lib/utils/cn";

export function PageHeader({
  actions,
  description,
  eyebrow,
  title,
}: {
  actions?: ReactNode;
  description: string;
  eyebrow?: string;
  title: string;
}) {
  return (
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
      <div>
        {eyebrow ? (
          <div className={cn("text-xs font-bold uppercase tracking-[0.14em]", "text-[var(--muted-foreground)]")}>
            {eyebrow}
          </div>
        ) : null}
        <h1 className="mt-1 text-4xl font-semibold tracking-tight text-[var(--foreground)]">{title}</h1>
        <p className="mt-2 max-w-3xl text-sm leading-7 text-[var(--muted-foreground)]">{description}</p>
      </div>

      {actions ? <div className="flex flex-wrap items-center gap-3">{actions}</div> : null}
    </div>
  );
}
