// apps/platform-web-vue/src/components/platform/TestcaseOverviewStrip.vue
<script setup lang="ts">
import { computed } from 'vue'
import MetricCard from '@/components/platform/MetricCard.vue'
import type { TestcaseOverview } from '@/types/management'
import { formatDateTime } from '@/utils/format'

const props = defineProps<{
  overview: TestcaseOverview | null
}>()

const items = computed(() => [
  {
    label: '正式用例',
    value: props.overview?.test_cases_total ?? 0,
    hint: props.overview?.latest_batch_id || '无批次',
    icon: 'testcase',
    tone: 'primary'
  },
  {
    label: '解析文档',
    value: props.overview?.documents_total ?? 0,
    hint: `parsed=${props.overview?.parsed_documents_total ?? 0}`,
    icon: 'folder',
    tone: 'success'
  },
  {
    label: '失败文档',
    value: props.overview?.failed_documents_total ?? 0,
    hint: (props.overview?.failed_documents_total ?? 0) > 0 ? '需要回看' : '状态正常',
    icon: 'activity',
    tone: 'warning'
  },
  {
    label: '最近活动',
    value: props.overview?.latest_activity_at ? formatDateTime(props.overview.latest_activity_at) : '--',
    hint: props.overview?.project_id || '未选择项目',
    icon: 'overview',
    tone: 'danger'
  }
])
</script>

<template>
  <div class="grid gap-3 xl:grid-cols-4">
    <MetricCard
      v-for="item in items"
      :key="item.label"
      :label="item.label"
      :value="item.value"
      :hint="item.hint"
      :icon="item.icon"
      :tone="item.tone"
    />
  </div>
</template>

// apps/platform-web-v2/src/components/platform/testcase-overview-strip.tsx
"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { TestcaseOverview } from "@/lib/management-api/testcase";

function formatDateTime(value?: string | null) {
  if (!value) {
    return "-";
  }
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return value;
  }
  return date.toLocaleString();
}

export function TestcaseOverviewStrip({ overview }: { overview: TestcaseOverview | null }) {
  const items = [
    {
      label: "正式用例",
      value: String(overview?.test_cases_total ?? 0),
      meta: overview?.latest_batch_id ?? "无批次",
    },
    {
      label: "解析文档",
      value: String(overview?.documents_total ?? 0),
      meta: `parsed=${overview?.parsed_documents_total ?? 0}`,
    },
    {
      label: "失败文档",
      value: String(overview?.failed_documents_total ?? 0),
      meta: overview?.failed_documents_total ? "需要回看" : "状态正常",
    },
    {
      label: "最近活动",
      value: formatDateTime(overview?.latest_activity_at),
      meta: overview?.project_id || "未选择项目",
    },
  ];

  return (
    <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
      {items.map((item) => (
        <Card key={item.label} className="gap-3 py-4">
          <CardHeader className="px-4">
            <CardTitle className="text-sm font-medium text-muted-foreground">{item.label}</CardTitle>
          </CardHeader>
          <CardContent className="px-4">
            <div className="text-lg font-semibold tracking-tight">{item.value}</div>
            <div className="mt-1 text-xs text-muted-foreground">{item.meta}</div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
